name: CI

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write

jobs:
  check_and_build:
    name: Clippy and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install development libraries
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-hp-build-${{ hashFiles('**/Cargo.toml') }}
          cache-on-failure: true

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

      - name: Setup Trunk
        run: cargo install --locked trunk

      - name: Build
        run: trunk build -d public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: check_and_build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
